### ISSUE TITLE
10x & Seurat: simple vignette

### ISSUE THREAD

**Issue by floriankreten** [dkzhang777/SlideCNA_Analysis#2]
Dear authors,

currently I want to compare & test different methods for CNV-calling on spatial 10x slides. Could you please provide a simple vignette for 10x data and seurat without any additional deconvolution steps? Just plain rough clustering (e.g. "tumor_cells", "reference_cells", "others") and then CNV-calling. I find it really difficult to get the inputs (metadata) into the correct format, the documentation is a bit rough to follow about that (I know that this package is quite new, so no offense here :) ).

Thanks in advance!

**Comment by dkzhang777** [comment]
Hi, thank you for the feedback! Unfortunately as of now, since SlideCNA was not developed for 10x Visium which has larger spots, we are not focusing on creating a vignette for that case although in the future this may be something to look at. However, we are happy to help you out if you can pinpoint a specific problem with the metadata formatting.
